(cl:in-package planning-srv)
(cl:export '(OBJ_POSX-VAL
          OBJ_POSX
          OBJ_POSY-VAL
          OBJ_POSY
          OBJ_POSZ-VAL
          OBJ_POSZ
          OBJ_ORIENTX-VAL
          OBJ_ORIENTX
          OBJ_ORIENTY-VAL
          OBJ_ORIENTY
          OBJ_ORIENTZ-VAL
          OBJ_ORIENTZ
          OBJ_ORIENTW-VAL
          OBJ_ORIENTW
          SIZEX-VAL
          SIZEX
          SIZEY-VAL
          SIZEY
          SIZEZ-VAL
          SIZEZ
          NAME_OBJ-VAL
          NAME_OBJ
          ORIENT-VAL
          ORIENT
          GOAL-VAL
          GOAL
          RESPONSE-VAL
          RESPONSE
))