// Generated by gencpp from file planning/enviro.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_ENVIRO_H
#define PLANNING_MESSAGE_ENVIRO_H

#include <ros/service_traits.h>


#include <planning/enviroRequest.h>
#include <planning/enviroResponse.h>


namespace planning
{

struct enviro
{

typedef enviroRequest Request;
typedef enviroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct enviro
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::enviro > {
  static const char* value()
  {
    return "7057eb40c64cbf8bdf2c3deb4aec57bb";
  }

  static const char* value(const ::planning::enviro&) { return value(); }
};

template<>
struct DataType< ::planning::enviro > {
  static const char* value()
  {
    return "planning/enviro";
  }

  static const char* value(const ::planning::enviro&) { return value(); }
};


// service_traits::MD5Sum< ::planning::enviroRequest> should match
// service_traits::MD5Sum< ::planning::enviro >
template<>
struct MD5Sum< ::planning::enviroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::enviro >::value();
  }
  static const char* value(const ::planning::enviroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::enviroRequest> should match
// service_traits::DataType< ::planning::enviro >
template<>
struct DataType< ::planning::enviroRequest>
{
  static const char* value()
  {
    return DataType< ::planning::enviro >::value();
  }
  static const char* value(const ::planning::enviroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::enviroResponse> should match
// service_traits::MD5Sum< ::planning::enviro >
template<>
struct MD5Sum< ::planning::enviroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::enviro >::value();
  }
  static const char* value(const ::planning::enviroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::enviroResponse> should match
// service_traits::DataType< ::planning::enviro >
template<>
struct DataType< ::planning::enviroResponse>
{
  static const char* value()
  {
    return DataType< ::planning::enviro >::value();
  }
  static const char* value(const ::planning::enviroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_ENVIRO_H
