// Generated by gencpp from file planning/gripRequest.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_GRIPREQUEST_H
#define PLANNING_MESSAGE_GRIPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct gripRequest_
{
  typedef gripRequest_<ContainerAllocator> Type;

  gripRequest_()
    : grip(false)  {
    }
  gripRequest_(const ContainerAllocator& _alloc)
    : grip(false)  {
  (void)_alloc;
    }



   typedef uint8_t _grip_type;
  _grip_type grip;





  typedef boost::shared_ptr< ::planning::gripRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::gripRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gripRequest_

typedef ::planning::gripRequest_<std::allocator<void> > gripRequest;

typedef boost::shared_ptr< ::planning::gripRequest > gripRequestPtr;
typedef boost::shared_ptr< ::planning::gripRequest const> gripRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::gripRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::gripRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planning::gripRequest_<ContainerAllocator1> & lhs, const ::planning::gripRequest_<ContainerAllocator2> & rhs)
{
  return lhs.grip == rhs.grip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planning::gripRequest_<ContainerAllocator1> & lhs, const ::planning::gripRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planning::gripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::gripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::gripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::gripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::gripRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::gripRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::gripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37d7db658f4389534cee042d68fbe2d2";
  }

  static const char* value(const ::planning::gripRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37d7db658f438953ULL;
  static const uint64_t static_value2 = 0x4cee042d68fbe2d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::gripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/gripRequest";
  }

  static const char* value(const ::planning::gripRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::gripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request message types\n"
"bool grip\n"
"\n"
;
  }

  static const char* value(const ::planning::gripRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::gripRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::gripRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::gripRequest_<ContainerAllocator>& v)
  {
    s << indent << "grip: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_GRIPREQUEST_H
