// Generated by gencpp from file planning/scale_msg.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_SCALE_MSG_H
#define PLANNING_MESSAGE_SCALE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct scale_msg_
{
  typedef scale_msg_<ContainerAllocator> Type;

  scale_msg_()
    : mass(0.0)  {
    }
  scale_msg_(const ContainerAllocator& _alloc)
    : mass(0.0)  {
  (void)_alloc;
    }



   typedef float _mass_type;
  _mass_type mass;





  typedef boost::shared_ptr< ::planning::scale_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::scale_msg_<ContainerAllocator> const> ConstPtr;

}; // struct scale_msg_

typedef ::planning::scale_msg_<std::allocator<void> > scale_msg;

typedef boost::shared_ptr< ::planning::scale_msg > scale_msgPtr;
typedef boost::shared_ptr< ::planning::scale_msg const> scale_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::scale_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::scale_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planning::scale_msg_<ContainerAllocator1> & lhs, const ::planning::scale_msg_<ContainerAllocator2> & rhs)
{
  return lhs.mass == rhs.mass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planning::scale_msg_<ContainerAllocator1> & lhs, const ::planning::scale_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planning::scale_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::scale_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::scale_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::scale_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::scale_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::scale_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::scale_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc896cc245a01cb882740a335971513f";
  }

  static const char* value(const ::planning::scale_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc896cc245a01cb8ULL;
  static const uint64_t static_value2 = 0x82740a335971513fULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::scale_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/scale_msg";
  }

  static const char* value(const ::planning::scale_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::scale_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 mass\n"
;
  }

  static const char* value(const ::planning::scale_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::scale_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scale_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::scale_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::scale_msg_<ContainerAllocator>& v)
  {
    s << indent << "mass: ";
    Printer<float>::stream(s, indent + "  ", v.mass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_SCALE_MSG_H
